<a href="https://colab.research.google.com/github/sebinsaji007/deep_learning-_journey/blob/main/Gradient_Descent_For_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
cd /content/drive/MyDrive/python/deep learning/gradient descent

/content/drive/MyDrive/python/deep learning/gradient descent


In [3]:
df = pd.read_csv('insurance_data (1).csv')

In [4]:
df.head()

X = df[['age','affordibility']]
y = df.bought_insurance

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

In [6]:
X_train_scaled = X_train
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test
X_test_scaled['age'] = X_test_scaled['age']/100

,kernel_initializer is setting intial value for weight as one and bias is setting value for intercept as 0

In [7]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2, ),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

In [8]:

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_scaled,y_train,epochs=5000)

Streaming output truncated to the last 5000 lines.
Epoch 1675/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5728 - accuracy: 0.6818
Epoch 1676/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.5728 - accuracy: 0.6818
Epoch 1677/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.5727 - accuracy: 0.6818
Epoch 1678/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5727 - accuracy: 0.6818
Epoch 1679/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5727 - accuracy: 0.6818
Epoch 1680/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5726 - accuracy: 0.6818
Epoch 1681/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5726 - accuracy: 0.6818
Epoch 1682/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5725 - accuracy: 0.6818
Epoch 1683/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5725 - accuracy: 0.6818
Epoch 1684/5000
1/1 [=============

In [9]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 186ms/step


array([[0.13749155],
       [0.38183627],
       [0.605982  ],
       [0.7682819 ],
       [0.4611073 ],
       [0.14328481]], dtype=float32)

In [10]:
y_test

1     0
20    0
22    1
5     1
7     1
21    0
Name: bought_insurance, dtype: int64

In [11]:
coef,intercept = model.get_weights()
coef,intercept

(array([[4.801133 ],
        [1.5465662]], dtype=float32),
 array([-3.0365658], dtype=float32))